### ISSUE TITLE
Distribution: set package distribution via PyPI up

### ISSUE THREAD

**Issue by rdnfn** [ai4er-cdt/gtc-biodiversity#57]
**Description:** make the GeoGraph package installable via pip by adding it to PyPI (Python Package Index). This will significantly increase the potential reach of our project, and make it super easy for people to try.

**Tasks:**
 To do this a few minimal requirements need to be meet
- [ ] We need to define our basic package description using `setuptools` package or similar
    - [ ] Introduce our own versioning (probably starting with 0.0.1)
    - [ ] Define package (not dev) dependencies, ideally as few and as flexibly as possible
- [ ] We need to build the package and upload it to PyPI (having registered before)

Additionally, it would be great to have some of these features
- [ ] Introduce testing to our package (e.g. using pytest), in the beginning this doesn't need to be a proper unit test setup: it could just be a few tests if the code will run without errors. That would be especially useful to determine the range of dependencies we're able to work with.

Sources:
- Talk on PyPI package creation: https://www.youtube.com/watch?v=GIF3LaRqgXo

**Comment by Croydon-Brixton** [comment]
Cleanup of the main branch for PyPI packaging and binder is [here](https://github.com/ai4er-cdt/gtc-biodiversity/tree/clean/cleanup-for-pip)
